### ISSUE TITLE
App crash during startup 

### ISSUE THREAD

**Issue by soumyabratabose** [lopez05656/LineageOS-Eleven-Material-Theme#6]
The log file is given below.

java.lang.RuntimeException: Unable to resume activity {org.lineageos.eleven/org.lineageos.eleven.ui.activities.HomeActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {org.lineageos.eleven/org.lineageos.eleven.ui.activities.HomeActivity}: android.view.InflateException: Binary XML file line #87 in org.lineageos.eleven:layout/activity_base: Binary XML file line #87 in org.lineageos.eleven:layout/activity_base: Error inflating class fragment
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4270)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4302)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {org.lineageos.eleven/org.lineageos.eleven.ui.activities.HomeActivity}: android.view.InflateException: Binary XML file line #87 in org.lineageos.eleven:layout/activity_base: Binary XML file line #87 in org.lineageos.eleven:layout/activity_base: Error inflating class fragment
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4938)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4257)
	... 11 more
Caused by: android.view.InflateException: Binary XML file line #87 in org.lineageos.eleven:layout/activity_base: Binary XML file line #87 in org.lineageos.eleven:layout/activity_base: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #87 in org.lineageos.eleven:layout/activity_base: Error inflating class fragment
Caused by: java.lang.IllegalArgumentException: Binary XML file line #87: Duplicate id 0x7f0a0079, tag null, or parent id 0x7f0a00f7 with another fragment for org.lineageos.eleven.ui.fragments.AudioPlayerFragment
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:116)
	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:319)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:298)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
	at org.lineageos.eleven.ui.activities.BaseActivity.init(BaseActivity.java:134)
	at org.lineageos.eleven.ui.activities.SlidingPanelActivity.init(SlidingPanelActivity.java:93)
	at org.lineageos.eleven.ui.activities.HomeActivity.init(HomeActivity.java:112)
	at org.lineageos.eleven.ui.activities.HomeActivity.onRequestPermissionsResult(HomeActivity.java:516)
	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8408)
	at android.app.Activity.dispatchActivityResult(Activity.java:8253)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4931)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4257)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4302)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by BlueN1nja1** [comment]
Thanks for the log. This bug will be fixed in the next beta release, Keep an eye out for 6.0.0 Beta 2.1. That beta will fix the crash bug.

**Comment by BlueN1nja1** [comment]
As of now, this bug is now fixed as of 6.0.0 Beta 2.1! This issue is now closed.
